[package]
name = "rust"
version = "0.1.0"
authors = ["Vorlent <vorlent@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.1"
ndarray = { version = "0.13.1", features = ["rayon"] }
